services:
  punctuation-inference:
    build:
      # dockerfile is located at punctuation-inference/Dockerfile
      context: punctuation-inference
    environment:
      - RUST_LOG=info
  speech-to-text:
    build:
      # dockerfile is located at speech-to-text/Dockerfile
      context: speech-to-text
    environment:
      - ENVIRONMENT=production
      - PULSE_SERVER=unix:/app/pulseaudio_socket
      - LOG_LEVEL=INFO
      # temporary debug variables
      # - SKIP_RECORDING=True
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    volumes:
      # attach the pulseaudio socket to the container
      - /run/user/1000/pulse/native:/app/pulseaudio_socket
      # also share where the whisper models are stored
      - ~/.cache/whisper:/root/.cache/whisper
      - ~/.cache/huggingface:/root/.cache/huggingface
  gesture-recognition:
    # the gesture recognition component needs to have access to the hosts webcam, and the X11 socket
    build:
      # dockerfile is located at gesture-recognition/Dockerfile
      context: gesture-recognition
    environment:
      - MODE=NORMAL # or "KEYPOINT_TRAINING" to generate training data
      # - MODE=KEYPOINT_TRAINING
      - LOG_LEVEL=INFO
      - DISPLAY=:0
      - PULSE_SERVER=unix:/app/pulseaudio_socket
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    volumes:
      # attach the keypoint csv file so that the training data can be saved
      - ./gesture-recognition/model/keypoint_classifier/keypoint.csv:/app/model/keypoint_classifier/keypoint.csv
      # attach the X11 socket to the container
      - /tmp/.X11-unix:/tmp/.X11-unix
      # attach the pulseaudio socket to the container
      - /run/user/1000/pulse/native:/app/pulseaudio_socket
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
