services:
  punctuation-inference:
    build:
      # dockerfile is located at punctuation-inference/Dockerfile
      context: punctuation-inference
    environment:
      - RUST_LOG=info
  speech-to-text:
    build:
      # dockerfile is located at speech-to-text/Dockerfile
      context: speech-to-text
    environment:
      - ENVIRONMENT=production
      - PULSE_SERVER=unix:/app/pulseaudio_socket
      # temporary debug variables
      # - SKIP_RECORDING=True
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    volumes:
      # attach the pulseaudio socket to the container
      - /run/user/1000/pulse/native:/app/pulseaudio_socket
      # also share where the whisper models are stored
      - ~/.cache/whisper:/root/.cache/whisper
      - ~/.cache/huggingface:/root/.cache/huggingface
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
